name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest

      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.3.0'
      
      - name: Install dependencies
        run: npm install

      - run: npm run build --if-present
      - run: npm test 
